#!/usr/bin/env python3
"""Generate the site's logo assets for a given tournament year.

Everything is derived from one file, `assets/logo-master/emblem_master.png` —
the 1024x1024 original artwork. Only two things change from year to year, and
both sit in the clear gap at the bottom of the circle:

    "20th Annual"   maroon script
    "2025"          navy numerals

This script masks those two blocks out and re-typesets them, then composes the
masthead banner and the homepage crest around the result. Nothing is
regenerated by an image model, so the emblem never drifts between years.

Usage:
    python build_logo_assets.py --year 2026 --ordinal 21st

Writes:
    assets/img/jl_logo_<year>_banner_memorial.png         1278x392 masthead
    images/jl_logo_<year>_transparent_smooth.png           293x312 crest
    images/jl_logo_<year>_transparent_smooth_reduced.png   169x182 crest
"""

import argparse
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

REPO = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(REPO, "assets", "logo-master", "emblem_master.png")
FONTS = r"C:\Windows\Fonts"

# Ink sampled from the master.
MAROON = (0x5F, 0x1C, 0x2A)
NAVY = (0x1D, 0x2B, 0x41)
WORDMARK_INK = (0xEB, 0xEB, 0xEB)

# Search window for the year numerals, in master coordinates. It deliberately
# overlaps the arc ends; the digits are separated from them below rather than
# by cropping, because no rectangle contains one without clipping the other.
YEAR_WINDOW = (275, 870, 715, 999)

# Closest available matches to the hand-lettered originals.
ANNUAL_FONT = "BRUSHSCI.TTF"      # Brush Script MT
YEAR_FONT = "BOOKOSI.TTF"         # Bookman Old Style Italic
WORDMARK_FONT = "verdanab.ttf"   # matches the original wordmark's metrics

# The two concentric rings, fitted to the master. Angles use
# atan2(y - cy, x - cx) in degrees, so 90 is the bottom of the image. Both
# rings break at the bottom to clear the year text; the radius and its slope
# either side of the break are what let the missing arc be drawn back in.
RING_CENTRE = (497.0, 538.0)
RING_INK = (0x19, 0x27, 0x3D)
RINGS = (
    # r_lo r_hi   t0   r0      slope0   t1   r1      slope1  width
    (368,  406,   66,  381.9,  -0.242,  128, 385.7,  +0.308, 8.0),   # inner
    (406,  458,   68,  424.0,  -0.533,  120, 422.8,  +0.520, 8.2),   # outer
)

# Banner geometry measured from the 2025 banner so the header does not shift.
BANNER = (1278, 392)
EMBLEM_BOX = (11, 40, 270, 290)                  # x, y, w, h
WORDMARK_LINES = ["Joe Lucky", "Memorial", "Golf Tournament"]
WORDMARK_LEFT = 338
WORDMARK_TOP = 61
WORDMARK_PITCH = 107                             # baseline-to-baseline
WORDMARK_CAP = 69                                # cap height of lines 2 and 3

CREST_FULL = (293, 312)
CREST_REDUCED = (169, 182)

# The emblem is dark ink, but the masthead is dark slate. The 2025 banner
# solved this with a white halo behind the strokes; without it the emblem goes
# muddy against the header. The crest keeps no halo — it sits on white.
HALO_RADIUS = 2


def white_to_alpha(img):
    """Turn a white background into transparency, keeping the ink colour.

    The artwork is dark ink composited over white, so
    ``observed = ink*a + 255*(1-a)``. Estimating coverage from the darkest
    channel and dividing it back out reproduces the original exactly on a
    white background and degrades gracefully on any other.
    """
    rgb = np.asarray(img.convert("RGB")).astype(np.float32)
    alpha = (255.0 - rgb.min(axis=2)) / 255.0
    safe = np.where(alpha > 0, alpha, 1)[:, :, None]
    ink = np.clip((rgb - 255.0 * (1 - safe)) / safe, 0, 255)
    out = np.dstack([ink, alpha * 255]).astype(np.uint8)
    out[alpha * 255 < 8] = 0
    return Image.fromarray(out, "RGBA")


def fitted_font(text, filename, box_w, box_h):
    """Largest font size whose rendering still fits the box."""
    best, size = None, 8
    while size < 400:
        font = ImageFont.truetype(os.path.join(FONTS, filename), size)
        left, top, right, bottom = font.getbbox(text)
        if right - left > box_w or bottom - top > box_h:
            break
        best, size = font, size + 1
    return best or font


def draw_centred(canvas, text, filename, box, colour):
    """Render text scaled to fill box and centred within it."""
    x0, y0, x1, y1 = box
    font = fitted_font(text, filename, x1 - x0, y1 - y0)
    left, top, right, bottom = font.getbbox(text)
    x = x0 + ((x1 - x0) - (right - left)) // 2 - left
    y = y0 + ((y1 - y0) - (bottom - top)) // 2 - top
    ImageDraw.Draw(canvas).text((x, y), text, font=font, fill=colour + (255,))


def bbox_of(mask):
    ys, xs = np.where(mask)
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def grow_into_halo(mask, rgb, rounds=6, near_white=735):
    """Extend a mask over the antialiased fringe around its own strokes.

    The colour tests that isolate the year text only catch solid ink, leaving
    a pale outline behind. That went unnoticed while replacement text was
    drawn over the top, but shows as a ghost on the undated emblem. Growing
    one pixel at a time and intersecting with "not essentially white" follows
    each glyph's own fade to nothing, and stops at the white gap separating
    the text from the arcs rather than bleeding across it.
    """
    faint = rgb.sum(axis=2) < near_white
    grown = mask.copy()
    for _ in range(rounds):
        spread = np.zeros_like(grown)
        spread[1:, :] |= grown[:-1, :]
        spread[:-1, :] |= grown[1:, :]
        spread[:, 1:] |= grown[:, :-1]
        spread[:, :-1] |= grown[:, 1:]
        nxt = (grown | spread) & faint
        if (nxt == grown).all():
            break
        grown = nxt
    return grown


def annual_mask(rgb):
    """The maroon script. Maroon appears nowhere else in the artwork."""
    r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    return (rgb.sum(axis=2) < 700) & (r > g + 25) & (r > b + 25)


def year_mask(rgb):
    """The navy numerals, separated from the navy arcs that flank them.

    Inside the search window the digits are self-contained blobs, while the
    arcs run off its edges. Flooding inward from the border therefore reaches
    every arc pixel and no digit pixel; whatever the flood misses is the year.
    """
    x0, y0, x1, y1 = YEAR_WINDOW
    ink = np.zeros(rgb.shape[:2], dtype=bool)
    ink[y0:y1, x0:x1] = rgb[y0:y1, x0:x1].sum(axis=2) < 700

    h, w = ink.shape
    reached = np.zeros_like(ink)
    stack = [(y, x) for y in (y0, y1 - 1) for x in range(x0, x1) if ink[y, x]]
    stack += [(y, x) for x in (x0, x1 - 1) for y in range(y0, y1) if ink[y, x]]
    for p in stack:
        reached[p] = True
    while stack:
        y, x = stack.pop()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1),
                       (1, 1), (1, -1), (-1, 1), (-1, -1)):
            ny, nx = y + dy, x + dx
            if y0 <= ny < y1 and x0 <= nx < x1 and ink[ny, nx] \
                    and not reached[ny, nx]:
                reached[ny, nx] = True
                stack.append((ny, nx))
    return ink & ~reached


def polar(shape):
    """Radius and angle of every pixel about the ring centre."""
    cx, cy = RING_CENTRE
    yy, xx = np.mgrid[0:shape[0], 0:shape[1]]
    return (np.hypot(xx - cx, yy - cy),
            np.degrees(np.arctan2(yy - cy, xx - cx)) % 360)


def scrub_zone(rgb, boxes, pad=6):
    """Everything inside the year-text boxes that is not part of the artwork.

    Growing the ink masks over their own halo still leaves the palest fringe
    behind — invisible under replacement text, but a legible ghost on the
    undated emblem. Inside these boxes the only real artwork is the green
    descender of "Lucky" and the two navy rings passing through, so anything
    that is neither can go, however faint.
    """
    r, _ = polar(rgb.shape[:2])
    zone = np.zeros(rgb.shape[:2], bool)
    for x0, y0, x1, y1 in boxes:
        zone[max(0, y0-pad):y1+pad, max(0, x0-pad):x1+pad] = True

    red, green, blue = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    is_green = (green > red + 8) | (green > blue + 8)
    on_ring = np.zeros_like(zone)
    for r_lo, r_hi, *_ in RINGS:
        on_ring |= (r >= r_lo - 2) & (r <= r_hi + 2)

    return zone & ~is_green & ~on_ring & (rgb.sum(axis=2) < 764)


def hermite(t, p0, p1, m0, m1):
    t2, t3 = t * t, t * t * t
    return ((2*t3 - 3*t2 + 1) * p0 + (t3 - 2*t2 + t) * m0
            + (-2*t3 + 3*t2) * p1 + (t3 - t2) * m1)


def close_rings(rgb, overlap=3.0):
    """Draw each ring's missing bottom arc.

    A rotated copy of existing arc does not work: the rings wobble by several
    pixels, so the copy meets the originals at the wrong radius. Interpolating
    the centreline with a Hermite curve matched to the radius *and* its slope
    at both ends joins seamlessly, and running a little past each end replaces
    the tapered tips with full-width stroke.
    """
    r, th = polar(rgb.shape[:2])
    out = rgb.astype(float)
    for _, _, t0, r0, s0, t1, r1, s1, width in RINGS:
        span = t1 - t0
        centre = hermite(np.clip((th - t0) / span, 0, 1),
                         r0, r1, s0 * span, s1 * span)
        cover = np.clip(width / 2 + 0.5 - np.abs(r - centre), 0, 1)
        cover[(th < t0 - overlap) | (th > t1 + overlap)] = 0
        out = out * (1 - cover[..., None]) + np.array(RING_INK) * cover[..., None]
    return out.astype(np.uint8)


def build_emblem(year=None, ordinal=None, plain=False, closed=False):
    """The master with its year text replaced, on a transparent background.

    With plain=True the year text is removed and nothing put back, giving the
    undated emblem — the form to hand out for shirts, signage or anything that
    should not be pinned to one tournament.
    """
    plate = Image.open(MASTER).convert("RGB")
    rgb = np.asarray(plate).astype(int)

    annual, years = annual_mask(rgb), year_mask(rgb)
    annual_box, year_box = bbox_of(annual), bbox_of(years)

    # Erase by ink rather than by rectangle, so the descender of "Lucky" and
    # the arc ends that overlap these blocks survive untouched.
    erase = grow_into_halo(annual | years, rgb)
    cleared = np.asarray(plate).copy()
    cleared[erase] = (255, 255, 255)

    if plain:
        # Nothing will be drawn back over the fringe, so it has to go entirely.
        cleared[scrub_zone(cleared.astype(int), (annual_box, year_box))] = \
            (255, 255, 255)
        if closed:
            cleared = close_rings(cleared)

    plate = Image.fromarray(cleared)

    if not plain:
        draw_centred(plate, f"{ordinal} Annual", ANNUAL_FONT, annual_box, MAROON)
        draw_centred(plate, str(year), YEAR_FONT, year_box, NAVY)

    emblem = white_to_alpha(plate)
    return emblem.crop(emblem.getbbox())


def haloed(emblem, radius):
    """Lay a white outline behind the ink so it reads on the dark masthead."""
    pad = radius * 2
    base = Image.new("RGBA", (emblem.width + pad * 2, emblem.height + pad * 2),
                     (0, 0, 0, 0))
    base.alpha_composite(emblem, (pad, pad))

    spread = base.getchannel("A").filter(ImageFilter.MaxFilter(radius * 2 + 1))
    halo = Image.new("RGBA", base.size, (255, 255, 255, 0))
    halo.putalpha(spread)
    halo.alpha_composite(base)
    return halo


def build_banner(emblem):
    """Emblem on the left, white wordmark on the right, transparent behind."""
    canvas = Image.new("RGBA", BANNER, (0, 0, 0, 0))

    # Scale first, then halo: a radius applied at master resolution would be
    # reduced to a sub-pixel fringe by the time the emblem reaches banner size.
    x, y, w, h = EMBLEM_BOX
    pad = HALO_RADIUS * 2
    scaled = emblem.copy()
    scaled.thumbnail((w - pad * 2, h - pad * 2), Image.LANCZOS)
    scaled = haloed(scaled, HALO_RADIUS)
    canvas.alpha_composite(scaled, (x + (w - scaled.width) // 2,
                                    y + (h - scaled.height) // 2))

    draw = ImageDraw.Draw(canvas)
    for i, line in enumerate(WORDMARK_LINES):
        font = fitted_font("Golf Tournament", WORDMARK_FONT,
                           BANNER[0] - WORDMARK_LEFT - 20, WORDMARK_CAP)
        top = WORDMARK_TOP + i * WORDMARK_PITCH
        draw.text((WORDMARK_LEFT, top - font.getbbox(line)[1]), line,
                  font=font, fill=WORDMARK_INK + (255,))
    return canvas


def fit_into(img, box):
    scaled = img.copy()
    scaled.thumbnail(box, Image.LANCZOS)
    canvas = Image.new("RGBA", box, (0, 0, 0, 0))
    canvas.paste(scaled, ((box[0] - scaled.width) // 2,
                          (box[1] - scaled.height) // 2))
    return canvas


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--year", type=int)
    ap.add_argument("--ordinal",
                    help='e.g. "21st" — the annual count, not the year')
    ap.add_argument("--plain", metavar="DIR", nargs="?", const=".",
                    help="write the undated emblem to DIR instead of building "
                         "site assets (transparent and white-backed PNGs)")
    args = ap.parse_args()

    if args.plain is not None:
        out = os.path.abspath(args.plain)
        os.makedirs(out, exist_ok=True)
        written = []
        for closed in (False, True):
            emblem = build_emblem(plain=True, closed=closed)
            tag = "closed" if closed else "open"

            transparent = os.path.join(out, f"jl_logo_plain_{tag}_transparent.png")
            emblem.save(transparent)

            # Transparency renders as black in some document and email
            # clients, so ship a flattened copy alongside it.
            flat = Image.new("RGB", emblem.size, (255, 255, 255))
            flat.paste(emblem, mask=emblem.getchannel("A"))
            white = os.path.join(out, f"jl_logo_plain_{tag}_white.png")
            flat.save(white)
            written += [(transparent, emblem.size), (white, emblem.size)]

        for path, size in written:
            print(f"  {os.path.basename(path):<40} {size[0]}x{size[1]}"
                  f"  {os.path.getsize(path) // 1024} KB")
        print(f"\nwritten to {out}")
        return

    if args.year is None or args.ordinal is None:
        ap.error("--year and --ordinal are required unless --plain is given")

    emblem = build_emblem(args.year, args.ordinal)
    outputs = [
        (build_banner(emblem),
         f"assets/img/jl_logo_{args.year}_banner_memorial.png"),
        (fit_into(emblem, CREST_FULL),
         f"images/jl_logo_{args.year}_transparent_smooth.png"),
        (fit_into(emblem, CREST_REDUCED),
         f"images/jl_logo_{args.year}_transparent_smooth_reduced.png"),
    ]
    for img, rel in outputs:
        path = os.path.join(REPO, rel)
        img.save(path, optimize=True)
        print(f"{rel:<58} {img.width}x{img.height}  "
              f"{os.path.getsize(path) // 1024}KB")


if __name__ == "__main__":
    main()
