#!/usr/bin/env python3
"""Generate the site's logo assets for a given tournament year.

Everything is derived from one file, `assets/logo-master/emblem_master.png` —
the 1024x1024 original artwork. Only two things change from year to year, and
both sit in the clear gap at the bottom of the circle:

    "20th Annual"   maroon script
    "2025"          navy numerals

This script masks those two blocks out and re-typesets them, then composes the
masthead banner and the homepage crest around the result. Nothing is
regenerated by an image model, so the emblem never drifts between years.

Usage:
    python build_logo_assets.py --year 2026 --ordinal 21st

Writes:
    assets/img/jl_logo_<year>_banner_memorial.png         1278x392 masthead
    images/jl_logo_<year>_transparent_smooth.png           293x312 crest
    images/jl_logo_<year>_transparent_smooth_reduced.png   169x182 crest
"""

import argparse
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

REPO = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(REPO, "assets", "logo-master", "emblem_master.png")
FONTS = r"C:\Windows\Fonts"

# Ink sampled from the master.
MAROON = (0x5F, 0x1C, 0x2A)
NAVY = (0x1D, 0x2B, 0x41)
WORDMARK_INK = (0xEB, 0xEB, 0xEB)

# Search window for the year numerals, in master coordinates. It deliberately
# overlaps the arc ends; the digits are separated from them below rather than
# by cropping, because no rectangle contains one without clipping the other.
YEAR_WINDOW = (275, 870, 715, 999)

# Closest available matches to the hand-lettered originals.
ANNUAL_FONT = "BRUSHSCI.TTF"      # Brush Script MT
YEAR_FONT = "BOOKOSI.TTF"         # Bookman Old Style Italic
WORDMARK_FONT = "verdanab.ttf"   # matches the original wordmark's metrics

# Banner geometry measured from the 2025 banner so the header does not shift.
BANNER = (1278, 392)
EMBLEM_BOX = (11, 40, 270, 290)                  # x, y, w, h
WORDMARK_LINES = ["Joe Lucky", "Memorial", "Golf Tournament"]
WORDMARK_LEFT = 338
WORDMARK_TOP = 61
WORDMARK_PITCH = 107                             # baseline-to-baseline
WORDMARK_CAP = 69                                # cap height of lines 2 and 3

CREST_FULL = (293, 312)
CREST_REDUCED = (169, 182)

# The emblem is dark ink, but the masthead is dark slate. The 2025 banner
# solved this with a white halo behind the strokes; without it the emblem goes
# muddy against the header. The crest keeps no halo — it sits on white.
HALO_RADIUS = 2


def white_to_alpha(img):
    """Turn a white background into transparency, keeping the ink colour.

    The artwork is dark ink composited over white, so
    ``observed = ink*a + 255*(1-a)``. Estimating coverage from the darkest
    channel and dividing it back out reproduces the original exactly on a
    white background and degrades gracefully on any other.
    """
    rgb = np.asarray(img.convert("RGB")).astype(np.float32)
    alpha = (255.0 - rgb.min(axis=2)) / 255.0
    safe = np.where(alpha > 0, alpha, 1)[:, :, None]
    ink = np.clip((rgb - 255.0 * (1 - safe)) / safe, 0, 255)
    out = np.dstack([ink, alpha * 255]).astype(np.uint8)
    out[alpha * 255 < 8] = 0
    return Image.fromarray(out, "RGBA")


def fitted_font(text, filename, box_w, box_h):
    """Largest font size whose rendering still fits the box."""
    best, size = None, 8
    while size < 400:
        font = ImageFont.truetype(os.path.join(FONTS, filename), size)
        left, top, right, bottom = font.getbbox(text)
        if right - left > box_w or bottom - top > box_h:
            break
        best, size = font, size + 1
    return best or font


def draw_centred(canvas, text, filename, box, colour):
    """Render text scaled to fill box and centred within it."""
    x0, y0, x1, y1 = box
    font = fitted_font(text, filename, x1 - x0, y1 - y0)
    left, top, right, bottom = font.getbbox(text)
    x = x0 + ((x1 - x0) - (right - left)) // 2 - left
    y = y0 + ((y1 - y0) - (bottom - top)) // 2 - top
    ImageDraw.Draw(canvas).text((x, y), text, font=font, fill=colour + (255,))


def bbox_of(mask):
    ys, xs = np.where(mask)
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def annual_mask(rgb):
    """The maroon script. Maroon appears nowhere else in the artwork."""
    r, g, b = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    return (rgb.sum(axis=2) < 700) & (r > g + 25) & (r > b + 25)


def year_mask(rgb):
    """The navy numerals, separated from the navy arcs that flank them.

    Inside the search window the digits are self-contained blobs, while the
    arcs run off its edges. Flooding inward from the border therefore reaches
    every arc pixel and no digit pixel; whatever the flood misses is the year.
    """
    x0, y0, x1, y1 = YEAR_WINDOW
    ink = np.zeros(rgb.shape[:2], dtype=bool)
    ink[y0:y1, x0:x1] = rgb[y0:y1, x0:x1].sum(axis=2) < 700

    h, w = ink.shape
    reached = np.zeros_like(ink)
    stack = [(y, x) for y in (y0, y1 - 1) for x in range(x0, x1) if ink[y, x]]
    stack += [(y, x) for x in (x0, x1 - 1) for y in range(y0, y1) if ink[y, x]]
    for p in stack:
        reached[p] = True
    while stack:
        y, x = stack.pop()
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1),
                       (1, 1), (1, -1), (-1, 1), (-1, -1)):
            ny, nx = y + dy, x + dx
            if y0 <= ny < y1 and x0 <= nx < x1 and ink[ny, nx] \
                    and not reached[ny, nx]:
                reached[ny, nx] = True
                stack.append((ny, nx))
    return ink & ~reached


def build_emblem(year, ordinal):
    """The master with its year text replaced, on a transparent background."""
    plate = Image.open(MASTER).convert("RGB")
    rgb = np.asarray(plate).astype(int)

    annual, years = annual_mask(rgb), year_mask(rgb)
    annual_box, year_box = bbox_of(annual), bbox_of(years)

    # Erase by ink rather than by rectangle, so the descender of "Lucky" and
    # the arc ends that overlap these blocks survive untouched.
    cleared = np.asarray(plate).copy()
    cleared[annual | years] = (255, 255, 255)
    plate = Image.fromarray(cleared)

    draw_centred(plate, f"{ordinal} Annual", ANNUAL_FONT, annual_box, MAROON)
    draw_centred(plate, str(year), YEAR_FONT, year_box, NAVY)

    emblem = white_to_alpha(plate)
    return emblem.crop(emblem.getbbox())


def haloed(emblem, radius):
    """Lay a white outline behind the ink so it reads on the dark masthead."""
    pad = radius * 2
    base = Image.new("RGBA", (emblem.width + pad * 2, emblem.height + pad * 2),
                     (0, 0, 0, 0))
    base.alpha_composite(emblem, (pad, pad))

    spread = base.getchannel("A").filter(ImageFilter.MaxFilter(radius * 2 + 1))
    halo = Image.new("RGBA", base.size, (255, 255, 255, 0))
    halo.putalpha(spread)
    halo.alpha_composite(base)
    return halo


def build_banner(emblem):
    """Emblem on the left, white wordmark on the right, transparent behind."""
    canvas = Image.new("RGBA", BANNER, (0, 0, 0, 0))

    # Scale first, then halo: a radius applied at master resolution would be
    # reduced to a sub-pixel fringe by the time the emblem reaches banner size.
    x, y, w, h = EMBLEM_BOX
    pad = HALO_RADIUS * 2
    scaled = emblem.copy()
    scaled.thumbnail((w - pad * 2, h - pad * 2), Image.LANCZOS)
    scaled = haloed(scaled, HALO_RADIUS)
    canvas.alpha_composite(scaled, (x + (w - scaled.width) // 2,
                                    y + (h - scaled.height) // 2))

    draw = ImageDraw.Draw(canvas)
    for i, line in enumerate(WORDMARK_LINES):
        font = fitted_font("Golf Tournament", WORDMARK_FONT,
                           BANNER[0] - WORDMARK_LEFT - 20, WORDMARK_CAP)
        top = WORDMARK_TOP + i * WORDMARK_PITCH
        draw.text((WORDMARK_LEFT, top - font.getbbox(line)[1]), line,
                  font=font, fill=WORDMARK_INK + (255,))
    return canvas


def fit_into(img, box):
    scaled = img.copy()
    scaled.thumbnail(box, Image.LANCZOS)
    canvas = Image.new("RGBA", box, (0, 0, 0, 0))
    canvas.paste(scaled, ((box[0] - scaled.width) // 2,
                          (box[1] - scaled.height) // 2))
    return canvas


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--year", type=int, required=True)
    ap.add_argument("--ordinal", required=True,
                    help='e.g. "21st" — the annual count, not the year')
    args = ap.parse_args()

    emblem = build_emblem(args.year, args.ordinal)
    outputs = [
        (build_banner(emblem),
         f"assets/img/jl_logo_{args.year}_banner_memorial.png"),
        (fit_into(emblem, CREST_FULL),
         f"images/jl_logo_{args.year}_transparent_smooth.png"),
        (fit_into(emblem, CREST_REDUCED),
         f"images/jl_logo_{args.year}_transparent_smooth_reduced.png"),
    ]
    for img, rel in outputs:
        path = os.path.join(REPO, rel)
        img.save(path, optimize=True)
        print(f"{rel:<58} {img.width}x{img.height}  "
              f"{os.path.getsize(path) // 1024}KB")


if __name__ == "__main__":
    main()
